import type { Product, Category, GalleryItem } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-single',
    name: 'Single Canvas Prints',
    slug: 'single-canvas-prints',
    description: 'High-definition single panel personalized and artistic photo canvas prints wrapped over handcrafted pine wood frames.',
    image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 1,
  },
  {
    id: 'cat-multi',
    name: 'Multi-Panel & Splits',
    slug: 'multi-panel-splits',
    description: 'Stunning 3, 5, and 7 panel multi-piece canvas compositions that transform single images into wall statements.',
    image_url: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 2,
  },
  {
    id: 'cat-aesthetic',
    name: 'Aesthetic & Vastu Wall Art',
    slug: 'aesthetic-vastu-wall-art',
    description: 'Pinterest-inspired cozy decor & traditional Vastu art for positive energy in homes & offices across Nepal.',
    image_url: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 3,
  },
  {
    id: 'cat-tshirts',
    name: 'Customized T-Shirts & Apparel',
    slug: 'customized-t-shirts',
    description: '100% premium bio-washed cotton t-shirts customized with photo prints, typography, and logo graphic art.',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 4,
  },
  {
    id: 'cat-personalized',
    name: 'Personal & Family Photo Portraits',
    slug: 'personalized-photo-canvas',
    description: 'Turn your family moments, wedding portraits, baby pictures, and travel memories into timeless gallery canvas walls.',
    image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 5,
  },
  {
    id: 'cat-framed',
    name: 'Framed Art & Wall Decor',
    slug: 'framed-art-wall-decor',
    description: 'Sleek black, gold, and wooden floating framed artwork to bring modern luxury to any wall space.',
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 6,
  },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'p-classic-canvas',
    name: 'Classic Studio Gallery Canvas Wall Art',
    slug: 'classic-studio-gallery-canvas-wall-art',
    sku: 'AD-CAN-CLASSIC-01',
    description:
      'Turn your most cherished photos into a museum-quality classic canvas print. Printed on archival cotton canvas with vibrant, fade-resistant UV inks, stretched over handcrafted solid pine wood frames. Perfect for living rooms, bedrooms, and office gallery walls.',
    short_description:
      'High-definition classic single photo canvas wrap with handcrafted solid pine wood frame.',
    main_image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-single',
    tags: ['custom', 'single-canvas', 'gallery-wrap', 'photo-print', 'best-seller'],
    base_price_paisa: 180000,
    discount_price_paisa: 145000,
    stock: 50,
    material: '100% Archival Cotton Canvas & Solid Pine Wood Frame',
    weight_grams: 850,
    dimensions: '16" × 24" (Single Panel)',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    status: 'published',
    seo_title: 'Classic Studio Gallery Canvas Wall Art | Affordable Decoration Nepal',
    seo_description:
      'Order museum-quality classic photo canvas prints in Nepal. Custom size, vibrant colors, ready to hang delivery.',
  },
  {
    id: 'p1',
    name: 'Custom Photo Canvas Single Focal (12" × 18")',
    slug: 'custom-photo-canvas-single-focal-12x18',
    sku: 'AD-CAN-PHOTO-01',
    description:
      'High-definition personalized single photo canvas printed on premium cotton canvas. Ideal for personal portraits, wedding photos, and anniversary gifts.',
    short_description: 'Personalized single panel photo canvas wall art.',
    main_image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-single',
    tags: ['custom', 'single-canvas', 'photo-print'],
    base_price_paisa: 100000,
    discount_price_paisa: 95000,
    stock: 100,
    material: '1 Panel Premium Cotton Canvas',
    weight_grams: 600,
    dimensions: '12" × 18"',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: 'Custom Photo Canvas Single Focal | Affordable Decoration',
    seo_description: 'High definition single photo canvas delivered across Nepal.',
  },
  {
    id: 'p2',
    name: 'Pinterest Aesthetic Bedroom Photo Canvas (24" × 36")',
    slug: 'pinterest-aesthetic-bedroom-photo-canvas',
    sku: 'AD-CAN-PIN-02',
    description:
      'Cozy Pinterest-inspired wall photo canvas split for warm living rooms & bedrooms. Warm golden aesthetic colors created to elevate interior decor.',
    short_description: 'Warm aesthetic canvas print for bedroom wall decor.',
    main_image_url: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-aesthetic',
    tags: ['aesthetic', 'pinterest', 'bedroom-decor'],
    base_price_paisa: 200000,
    discount_price_paisa: 190000,
    stock: 30,
    material: 'Aesthetic Canvas Print',
    weight_grams: 1200,
    dimensions: '24" × 36"',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: 'Pinterest Aesthetic Bedroom Photo Canvas',
    seo_description: 'Cozy memory wall gallery and multi-panel photo split.',
  },
  {
    id: 'p3',
    name: '7 Running Horses Vastu 5-Panel Wall Canvas (60" × 32")',
    slug: '7-running-horses-vastu-5-panel-wall-canvas',
    sku: 'AD-CAN-7HORSES',
    description:
      'Breathtaking 5-piece staggered Vastu horse canvas for positive energy & prosperity. Designed in accordance with traditional Vastu Shastra principles for living room or office entrance.',
    short_description: 'Vastu 5-panel split canvas for living room.',
    main_image_url: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-multi',
    tags: ['vastu', '5-panel', 'horses', 'living-room'],
    base_price_paisa: 300000,
    discount_price_paisa: 285000,
    stock: 25,
    material: '5 Pieces Split Canvas',
    weight_grams: 2100,
    dimensions: '60" × 32" Total',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: '7 Running Horses Vastu 5-Panel Wall Canvas',
    seo_description: 'Staggered 5-panel Vastu horse artwork for home energy.',
  },
  {
    id: 'p4',
    name: 'Everest Sunset Himalayan Triptych Canvas (48" × 24")',
    slug: 'everest-sunset-himalayan-triptych-canvas',
    sku: 'AD-CAN-001',
    description:
      'Breathtaking 3-panel panoramic canvas of Mt. Everest bathed in golden sunset light. High contrast alpine photography printed on textured canvas.',
    short_description: 'Panoramic 3-piece mountain canvas wall art.',
    main_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-multi',
    tags: ['himalaya', 'triptych', 'landscape', 'mountain'],
    base_price_paisa: 250000,
    discount_price_paisa: 237500,
    stock: 40,
    material: '3 Pieces Triptych Canvas',
    weight_grams: 1600,
    dimensions: '48" × 24" Total',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: 'Everest Sunset Himalayan Triptych Canvas',
    seo_description: '3-panel panoramic Mt. Everest canvas print.',
  },
  {
    id: 'p5',
    name: 'Abstract Golden Forest Canvas (36" × 24")',
    slug: 'abstract-golden-forest-canvas',
    sku: 'AD-CAN-GOLD-05',
    description:
      'Modern luxury golden foil landscape canvas artwork to elevate your living room decor. Rich gold tones contrast against deep forest silhouettes.',
    short_description: 'Elegant abstract gold foliage artwork canvas.',
    main_image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-aesthetic',
    tags: ['abstract', 'gold', 'modern-art'],
    base_price_paisa: 220000,
    discount_price_paisa: 195000,
    stock: 20,
    material: 'Premium Stretched Canvas',
    weight_grams: 1100,
    dimensions: '36" × 24"',
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    status: 'published',
    seo_title: 'Abstract Golden Forest Canvas Art',
    seo_description: 'Luxury gold foil abstract landscape canvas print.',
  },
  {
    id: 'p6',
    name: 'Custom Graphic Printed Bio-Wash T-Shirt',
    slug: 'custom-graphic-printed-bio-wash-t-shirt',
    sku: 'AD-TSHIRT-01',
    description:
      'Ultra-soft 100% bio-washed combed cotton customized t-shirt. Direct-to-garment high definition printing that stays vibrant through hundreds of washes.',
    short_description: 'Personalized premium cotton graphic t-shirt.',
    main_image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-tshirts',
    tags: ['tshirt', 'custom', 'apparel', 'graphic-tee'],
    base_price_paisa: 120000,
    discount_price_paisa: 99900,
    stock: 150,
    material: '100% Combed Bio-Wash Cotton (180 GSM)',
    weight_grams: 220,
    dimensions: 'S, M, L, XL, XXL',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    status: 'published',
    seo_title: 'Custom Graphic Printed T-Shirt Nepal',
    seo_description: 'High quality customized t-shirt printing in Kathmandu Nepal.',
  },
  {
    id: 'p7',
    name: 'Cherished Family Memory Gallery Canvas (30" × 20")',
    slug: 'cherished-family-memory-gallery-canvas',
    sku: 'AD-CAN-FAM-01',
    description:
      'Turn your family portraits, children milestone photos, or wedding pictures into a centerpiece museum canvas for your living wall.',
    short_description: 'Custom family photo gallery canvas print.',
    main_image_url: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-personalized',
    tags: ['family', 'personalized', 'portrait', 'wedding-gift'],
    base_price_paisa: 210000,
    discount_price_paisa: 185000,
    stock: 60,
    material: 'Archival Matte Cotton Canvas Wrap',
    weight_grams: 1400,
    dimensions: '30" × 20"',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: 'Cherished Family Memory Gallery Canvas',
    seo_description: 'Custom family portrait and memory wall canvas print.',
  },
  {
    id: 'p8',
    name: 'Modern Floating Black Frame Wall Artwork (24" × 36")',
    slug: 'modern-floating-black-frame-wall-artwork',
    sku: 'AD-CAN-FRAME-01',
    description:
      'Premium canvas framed inside a sleek 35mm deep black composite floating frame, leaving an elegant shadow gap around the canvas.',
    short_description: 'Floating framed canvas wall decor artwork.',
    main_image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-framed',
    tags: ['framed', 'black-frame', 'floating-frame', 'modern-decor'],
    base_price_paisa: 280000,
    discount_price_paisa: 249000,
    stock: 35,
    material: 'Canvas with Matte Black Shadow Box Frame',
    weight_grams: 1900,
    dimensions: '24" × 36"',
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    status: 'published',
    seo_title: 'Modern Floating Black Frame Canvas Art',
    seo_description: 'Luxury floating black frame canvas print for living room walls.',
  },
];

export const DEFAULT_GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    image_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    caption: 'Classic Studio Gallery Canvas - Single Panel Wrap',
    category: 'Single Canvas Prints',
    is_featured: true,
    status: 'published',
    sort_order: 1,
  },
  {
    id: 'gal-2',
    image_url: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80',
    caption: '7 Running Horses Vastu 5-Panel Staggered Split',
    category: 'Multi-Panel & Splits',
    is_featured: true,
    status: 'published',
    sort_order: 2,
  },
  {
    id: 'gal-3',
    image_url: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
    caption: 'Pinterest Aesthetic Bedroom Cozy Wall Canvas',
    category: 'Aesthetic & Vastu Wall Art',
    is_featured: true,
    status: 'published',
    sort_order: 3,
  },
  {
    id: 'gal-4',
    image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    caption: 'Customized Graphic Printed Cotton T-Shirt',
    category: 'Customized T-Shirts & Apparel',
    is_featured: true,
    status: 'published',
    sort_order: 4,
  },
  {
    id: 'gal-5',
    image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    caption: 'Cherished Family Memory Wall Portrait Canvas',
    category: 'Personal & Family Photo Portraits',
    is_featured: true,
    status: 'published',
    sort_order: 5,
  },
  {
    id: 'gal-6',
    image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    caption: 'Everest Sunset Himalayan Triptych 3-Panel',
    category: 'Multi-Panel & Splits',
    is_featured: false,
    status: 'published',
    sort_order: 6,
  },
  {
    id: 'gal-7',
    image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    caption: 'Abstract Golden Forest Luxury Canvas Wall Art',
    category: 'Aesthetic & Vastu Wall Art',
    is_featured: false,
    status: 'published',
    sort_order: 7,
  },
  {
    id: 'gal-8',
    image_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    caption: 'Modern Black Floating Frame Wall Decor',
    category: 'Framed Art & Wall Decor',
    is_featured: true,
    status: 'published',
    sort_order: 8,
  },
];
