import type { Product, Category } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-single',
    name: 'Single Canvas Prints',
    slug: 'single-canvas-prints',
    description: 'High-definition single panel personalized and artistic photo canvas prints.',
    image_url: '/images/classic-canvas-gallery.jpg',
    parent_id: null,
    status: 'published',
    sort_order: 1,
  },
  {
    id: 'cat-multi',
    name: 'Multi-Panel & Splits',
    slug: 'multi-panel-splits',
    description: 'Stunning 3, 5, and 7 panel multi-piece canvas compositions.',
    image_url: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 2,
  },
  {
    id: 'cat-aesthetic',
    name: 'Aesthetic & Vastu Wall Art',
    slug: 'aesthetic-vastu-wall-art',
    description: 'Pinterest-inspired cozy decor & traditional Vastu art for homes & offices across Nepal.',
    image_url: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
    parent_id: null,
    status: 'published',
    sort_order: 3,
  },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'p-classic-canvas',
    name: 'Classic Studio Gallery Canvas Wall Art',
    slug: 'classic-studio-gallery-canvas-wall-art',
    sku: 'AD-CAN-CLASSIC-01',
    description:
      'Turn your most cherished photos into a museum-quality classic canvas print. Printed on archival cotton canvas with vibrant, fade-resistant UV inks, stretched over handcrafted solid pine wood frames. Perfect for living rooms, bedrooms, and office gallery walls.',
    short_description:
      'High-definition classic single photo canvas wrap with handcrafted solid pine wood frame.',
    main_image_url: '/images/classic-canvas-gallery.jpg',
    category_id: 'cat-single',
    tags: ['custom', 'single-canvas', 'gallery-wrap', 'photo-print', 'best-seller'],
    base_price_paisa: 180000,
    discount_price_paisa: 145000,
    stock: 50,
    material: '100% Archival Cotton Canvas & Solid Pine Wood Frame',
    weight_grams: 850,
    dimensions: '16" × 24" (Single Panel)',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: true,
    status: 'published',
    seo_title: 'Classic Studio Gallery Canvas Wall Art | Affordable Decoration Nepal',
    seo_description:
      'Order museum-quality classic photo canvas prints in Nepal. Custom size, vibrant colors, ready to hang delivery.',
  },
  {
    id: 'p1',
    name: 'Custom Photo Canvas Single Focal (12" × 18")',
    slug: 'custom-photo-canvas-single-focal-12x18',
    sku: 'AD-CAN-PHOTO-01',
    description:
      'High-definition personalized single photo canvas printed on premium cotton canvas. Ideal for personal portraits, wedding photos, and anniversary gifts.',
    short_description: 'Personalized single panel photo canvas wall art.',
    main_image_url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-single',
    tags: ['custom', 'single-canvas', 'photo-print'],
    base_price_paisa: 100000,
    discount_price_paisa: 95000,
    stock: 100,
    material: '1 Panel Premium Cotton Canvas',
    weight_grams: 600,
    dimensions: '12" × 18"',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: 'Custom Photo Canvas Single Focal | Affordable Decoration',
    seo_description: 'High definition single photo canvas delivered across Nepal.',
  },
  {
    id: 'p2',
    name: 'Pinterest Aesthetic Bedroom Photo Canvas (24" × 36")',
    slug: 'pinterest-aesthetic-bedroom-photo-canvas',
    sku: 'AD-CAN-PIN-02',
    description:
      'Cozy Pinterest-inspired wall photo canvas split for warm living rooms & bedrooms. Warm golden aesthetic colors created to elevate interior decor.',
    short_description: 'Warm aesthetic canvas print for bedroom wall decor.',
    main_image_url: 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-aesthetic',
    tags: ['aesthetic', 'pinterest', 'bedroom-decor'],
    base_price_paisa: 200000,
    discount_price_paisa: 190000,
    stock: 30,
    material: 'Aesthetic Canvas Print',
    weight_grams: 1200,
    dimensions: '24" × 36"',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: 'Pinterest Aesthetic Bedroom Photo Canvas',
    seo_description: 'Cozy memory wall gallery and multi-panel photo split.',
  },
  {
    id: 'p3',
    name: '7 Running Horses Vastu 5-Panel Wall Canvas (60" × 32")',
    slug: '7-running-horses-vastu-5-panel-wall-canvas',
    sku: 'AD-CAN-7HORSES',
    description:
      'Breathtaking 5-piece staggered Vastu horse canvas for positive energy & prosperity. Designed in accordance with traditional Vastu Shastra principles for living room or office entrance.',
    short_description: 'Vastu 5-panel split canvas for living room.',
    main_image_url: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-multi',
    tags: ['vastu', '5-panel', 'horses', 'living-room'],
    base_price_paisa: 300000,
    discount_price_paisa: 285000,
    stock: 25,
    material: '5 Pieces Split Canvas',
    weight_grams: 2100,
    dimensions: '60" × 32" Total',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: '7 Running Horses Vastu 5-Panel Wall Canvas',
    seo_description: 'Staggered 5-panel Vastu horse artwork for home energy.',
  },
  {
    id: 'p4',
    name: 'Everest Sunset Himalayan Triptych Canvas (48" × 24")',
    slug: 'everest-sunset-himalayan-triptych-canvas',
    sku: 'AD-CAN-001',
    description:
      'Breathtaking 3-panel panoramic canvas of Mt. Everest bathed in golden sunset light. High contrast alpine photography printed on textured canvas.',
    short_description: 'Panoramic 3-piece mountain canvas wall art.',
    main_image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-multi',
    tags: ['himalaya', 'triptych', 'landscape', 'mountain'],
    base_price_paisa: 250000,
    discount_price_paisa: 237500,
    stock: 40,
    material: '3 Pieces Triptych Canvas',
    weight_grams: 1600,
    dimensions: '48" × 24" Total',
    is_featured: true,
    is_best_seller: true,
    is_new_arrival: false,
    status: 'published',
    seo_title: 'Everest Sunset Himalayan Triptych Canvas',
    seo_description: '3-panel panoramic Mt. Everest canvas print.',
  },
  {
    id: 'p5',
    name: 'Abstract Golden Forest Canvas (36" × 24")',
    slug: 'abstract-golden-forest-canvas',
    sku: 'AD-CAN-GOLD-05',
    description:
      'Modern luxury golden foil landscape canvas artwork to elevate your living room decor. Rich gold tones contrast against deep forest silhouettes.',
    short_description: 'Elegant abstract gold foliage artwork canvas.',
    main_image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    category_id: 'cat-aesthetic',
    tags: ['abstract', 'gold', 'modern-art'],
    base_price_paisa: 220000,
    discount_price_paisa: 195000,
    stock: 20,
    material: 'Premium Stretched Canvas',
    weight_grams: 1100,
    dimensions: '36" × 24"',
    is_featured: true,
    is_best_seller: false,
    is_new_arrival: true,
    status: 'published',
    seo_title: 'Abstract Golden Forest Canvas Art',
    seo_description: 'Luxury gold foil abstract landscape canvas print.',
  },
];
